services:
  - type: web
    name: mon-site-films-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: "mongodb+srv://cissou:cissou@cluster0.n2o3u.mongodb.net/ciii"
      - key: GOOGLE_CLIENT_ID
        value: "1016428156112-5k707l5g780vkj5sfn1palc54nsq69vj.apps.googleusercontent.com"
      - key: GOOGLE_CLIENT_SECRET
        value: "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"
      - key: GOOGLE_REDIRECT_URI
        value: "http://localhost:5001/auth/google/callback"
      - key: SESSION_SECRET
        value: "monsecret"
      - key: PORT
        value: "5001"
      - key: EMAIL_USER
        value: "abdessatarbourai@gmail.com"
      - key: EMAIL_PASS
        value: "qugb uxzb gudl wsfe"
      - key: TMDB_API_KEY
        value: "4a7fa7389e9a4ceeef5a953ff90232df"
      - key: RECAPTCHA_SECRET_KEY
        value: "6LcIsfEqAAAAAEqDk6s22WVzAhpljom1JCNU7PnV"
    autoDeploy: true
    